name: Deploy

on:
  push:
    branches: [prod, dev, dev2]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull on VDS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: 5.35.85.220
          username: user
          key: ${{ secrets.VDS_SSH_KEY }}
          script: /home/user/bin/bereg-git-deploy ${{ github.ref_name }}
